### PR TITLE
script to run a general cmd with service account credential

### PR DESCRIPTION
**Pull request by yachang**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/travis/47)

### CODE REVIEW

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/travis/47)* status: 0 of 1 LGTMs obtained

___
*[general_cmd.sh, line 1 at r1](https://reviewable.io/reviews/m-lab/travis/47#-M-l0RQn6s0rObzl4CY5:-M-l0RQoA3O_lKoM0rR6:blwyook) ([raw file](https://github.com/m-lab/travis/blob/72f10b45e5d67d4d33d714d79f1c9bde725abc84/general_cmd.sh#L1)):*
> ```Shell
> #!/bin/bash
> ```

Please rename script to something that clarifies what makes it unique -- this script exists to run a command with `GOOGLE_APPLICTION_CREDENTIALS` set.

Maybe name it something like

* run_with_application_credentials.sh
* 
___
*[general_cmd.sh, line 12 at r1](https://reviewable.io/reviews/m-lab/travis/47#-M-l0znHCNhaTqwya4tS:-M-l0znI3u1mOsKj8RFA:b5iqdpd) ([raw file](https://github.com/m-lab/travis/blob/72f10b45e5d67d4d33d714d79f1c9bde725abc84/general_cmd.sh#L12)):*
> ```Shell
> BASEDIR=${3:?Please provide the path to the command to run}
> CMD=${4:?Please provide the binary name to run}
> TRAVIS_COMMIT=${TRAVIS_COMMIT:-unknown}
> ```

Please eliminate variables that are not used by this script.
___
*[general_cmd.sh, line 22 at r1](https://reviewable.io/reviews/m-lab/travis/47#-M-l12P8CVbheOl8KAUF:-M-l12P8CVbheOl8KAUG:bn977dj) ([raw file](https://github.com/m-lab/travis/blob/72f10b45e5d67d4d33d714d79f1c9bde725abc84/general_cmd.sh#L22)):*
> ```Shell
> 
> # Authenticate all operations using the given service account.
> activate_service_account "${KEYNAME}"
> ```

I suggest removing this and the other gcloud commands b/c this script is meant to run command that need GOOGLE_APPLICATION_CREDENTIALS not the gcloud environment.

**Review by yachang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/travis/47)* status: 0 of 1 LGTMs obtained

___
*[general_cmd.sh, line 12 at r1](https://reviewable.io/reviews/m-lab/travis/47#-M-l0znHCNhaTqwya4tS:-M-owwdeAN-vsSDanNRi:b-896fix) ([raw file](https://github.com/m-lab/travis/blob/72f10b45e5d67d4d33d714d79f1c9bde725abc84/general_cmd.sh#L12)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please eliminate variables that are not used by this script.
</blockquote></details>

Done.
___
*[general_cmd.sh, line 22 at r1](https://reviewable.io/reviews/m-lab/travis/47#-M-l12P8CVbheOl8KAUF:-M-ox3fz-ARSKzDFGjeF:b-2unfvd) ([raw file](https://github.com/m-lab/travis/blob/72f10b45e5d67d4d33d714d79f1c9bde725abc84/general_cmd.sh#L22)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I suggest removing this and the other gcloud commands b/c this script is meant to run command that need GOOGLE_APPLICATION_CREDENTIALS not the gcloud environment.
</blockquote></details>

I will try and update here.

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/travis/47)* status: 0 of 1 LGTMs obtained

___
*[general_cmd.sh, line 22 at r1](https://reviewable.io/reviews/m-lab/travis/47#-M-l12P8CVbheOl8KAUF:-M-ozig7Agic6Cg0Vo3n:b2lyjph) ([raw file](https://github.com/m-lab/travis/blob/72f10b45e5d67d4d33d714d79f1c9bde725abc84/general_cmd.sh#L22)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

I will try and update here.
</blockquote></details>

I don't understand. What happens when the gcloud commands are eliminated?

**Review by yachang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/travis/47)* status: 0 of 1 LGTMs obtained

___
*[general_cmd.sh, line 22 at r1](https://reviewable.io/reviews/m-lab/travis/47#-M-l12P8CVbheOl8KAUF:-M-p3ojL41M-w3KZDAMp:b-mnoizz) ([raw file](https://github.com/m-lab/travis/blob/72f10b45e5d67d4d33d714d79f1c9bde725abc84/general_cmd.sh#L22)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I don't understand. What happens when the gcloud commands are eliminated?
</blockquote></details>

It is working with this test branch 

https://github.com/m-lab/etl/pull/814/

https://travis-ci.org/m-lab/etl/builds/648977411

So I have removed all gcloud related commands. Thanks!

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/travis/47)* status: 0 of 1 LGTMs obtained

___
*[run_with_application_credentials.sh, line 3 at r2](https://reviewable.io/reviews/m-lab/travis/47#-M-p3Q0s80dVzcvH6LJr:-M-p3Q0t7BlKhmLXpP8x:b-z41y55) ([raw file](https://github.com/m-lab/travis/blob/7724eee0a46e0fb856135acf325eeb64a03c2910/run_with_application_credentials.sh#L3)):*
> ```Shell
> #!/bin/bash
> #
> # Run a cmd using service account credentials.
> ```

"Run a cmd using service account credentials as application credentials."
___
*[run_with_application_credentials.sh, line 11 at r3](https://reviewable.io/reviews/m-lab/travis/47#-M-p5RZaCfMhH9zoe_p1:-M-p5RZaCfMhH9zoe_p2:bg2inkr) ([raw file](https://github.com/m-lab/travis/blob/1563e573c4a04fcd3d869300c747728f0cf3380b/run_with_application_credentials.sh#L11)):*
> ```Shell
> KEYNAME=${2:?Please provide the service account keyname}
> BASEDIR=${3:?Please provide the path to the command to run}
> CMD=${4:?Please provide the binary name to run}
> ```

To make this script generic and to allow future commands with parameters, it may be helpful to eliminate the fourth variable here in favor of using `$@` as in `kubectl.sh`.

So, I suggest removing `$CMD`, using `shift 3` here, and using `$@` (no quotes) on line below

```
GCLOUD_PROJECT="${PROJECT}" $@
```

This will work the same way and allow parameters.
___
*[run_with_application_credentials.sh, line 14 at r3](https://reviewable.io/reviews/m-lab/travis/47#-M-p3w2d0J13ySmwJN1Q:-M-p3w2d0J13ySmwJN1R:br67maa) ([raw file](https://github.com/m-lab/travis/blob/1563e573c4a04fcd3d869300c747728f0cf3380b/run_with_application_credentials.sh#L14)):*
> ```Shell
> 
> local keyfile=$( mktemp )
> set +x; echo "${!KEYNAME}" > ${keyfile}
> ```

`set +x` disables debug logging to prevent leaking the SA key.

Please enable debug logging again after this command so the script logs the remaining steps.

**Review by yachang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/travis/47)* status: 0 of 1 LGTMs obtained

___
*[run_with_application_credentials.sh, line 3 at r2](https://reviewable.io/reviews/m-lab/travis/47#-M-p3Q0s80dVzcvH6LJr:-M-pPPqc3oCu-BSyDj0_:b-896fix) ([raw file](https://github.com/m-lab/travis/blob/7724eee0a46e0fb856135acf325eeb64a03c2910/run_with_application_credentials.sh#L3)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

"Run a cmd using service account credentials as application credentials."
</blockquote></details>

Done.
___
*[run_with_application_credentials.sh, line 11 at r3](https://reviewable.io/reviews/m-lab/travis/47#-M-p5RZaCfMhH9zoe_p1:-M-pPr1L0gQCc_6jnFAf:b-896fix) ([raw file](https://github.com/m-lab/travis/blob/1563e573c4a04fcd3d869300c747728f0cf3380b/run_with_application_credentials.sh#L11)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

To make this script generic and to allow future commands with parameters, it may be helpful to eliminate the fourth variable here in favor of using `$@` as in `kubectl.sh`.

So, I suggest removing `$CMD`, using `shift 3` here, and using `$@` (no quotes) on line below

```
GCLOUD_PROJECT="${PROJECT}" $@
```

This will work the same way and allow parameters.
</blockquote></details>

Done.

**Review by yachang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/travis/47)* status: 0 of 1 LGTMs obtained

___
*[run_with_application_credentials.sh, line 14 at r3](https://reviewable.io/reviews/m-lab/travis/47#-M-p3w2d0J13ySmwJN1Q:-M-pbLLi3sqAZYr9bXy5:b-896fix) ([raw file](https://github.com/m-lab/travis/blob/1563e573c4a04fcd3d869300c747728f0cf3380b/run_with_application_credentials.sh#L14)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

`set +x` disables debug logging to prevent leaking the SA key.

Please enable debug logging again after this command so the script logs the remaining steps.
</blockquote></details>

Done.

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/m-lab/travis/47#-:-M-pbUL4DkJIE0WGeUVR:bnfp4nl)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
